// How to do the exercises people do most: a few cues for each, shown from the Tracker's ⋯ menu ("How to do it"). They are
// written for someone who has seen the lift before and wants the setup and the usual slip, not a course in it. An exercise
// of one's own, or one named in a way no entry matches, has no cues; the panel says so and still links to a video search.
//
// Each entry's `match` is tried against the name in order, and the first that fits (and whose `not`, if it has one, does not)
// is used, so a specific lift has to come before the general one it contains: a Romanian Deadlift before deadlifts, a
// Goblet Squat before squats. wordsIn is from exercise-library.js.

const exerciseGuides = [
  { title:'Single-Leg Romanian Deadlift', match:wordsIn(['single[- ]leg (\\w+ )*(romanian|rdls?)', 'one[- ]leg (\\w+ )*(romanian|rdls?)']),
    steps:['Stand on one leg with a soft knee and the weight in the opposite hand, or both hands.', 'Push your hips straight back as your free leg reaches behind you, the back flat.',
      'Lower until you feel the hamstring stretch, with the hips still square to the floor.', 'Squeeze the glute and stand tall to come up.'],
    mistake:'Opening the hips to the side or rounding the back to reach lower.' },
  { title:'Romanian Deadlift', match:wordsIn(['romanian', 'rdls?', 'stiff[- ]leg(ged)?']),
    steps:['Stand tall holding the weight against your thighs, feet hip-width apart, knees slightly bent.', 'Push your hips back, sliding the weight down your legs with a flat back.',
      'Stop when the hamstrings are stretched, usually just below the knee, with the bar still close.', 'Drive the hips forward to stand, squeezing the glutes at the top.'],
    mistake:'Bending the knees more on the way down, which turns it into a squat.' },
  { title:'Deadlift', match:wordsIn(['deadlifts?']),
    steps:['Bar over the middle of your feet, shins a few inches from it, feet about hip-width apart.', 'Hinge down and grip just outside your legs. Chest up, back flat, arms straight.',
      'Take the slack out of the bar, then push the floor away, keeping the bar against your legs.', 'Stand tall with the hips and knees locking out together, then lower it the way it came up.'],
    mistake:'Jerking the bar off the floor, or letting the hips shoot up first so the back does the lifting.' },
  { title:'Bulgarian Split Squat', match:wordsIn(['bulgarian', 'split squats?']),
    steps:['Rest the back foot on a bench behind you, the front foot far enough ahead that the shin stays near upright when you go down.',
      'Lean the torso slightly forward and keep the weight on the front foot.',
      'Lower straight down until the back knee nearly touches the floor.', 'Push through the whole front foot to stand.'],
    mistake:'Standing too close to the bench, which pushes the front knee far past the toes and strains it.' },
  { title:'Goblet Squat', match:wordsIn(['goblet']),
    steps:['Hold one dumbbell or kettlebell against your chest with both hands, elbows pointing down.', 'Feet a little wider than the shoulders, toes slightly out.',
      'Sit down between your knees, keeping the chest up and the elbows inside them.', 'Drive up through the middle of the foot.'],
    mistake:'Letting the weight pull you forward onto your toes.' },
  { title:'Front Squat', match:wordsIn(['front squats?']),
    steps:['Rest the bar on the front of your shoulders, fingers under it and elbows high so the upper arms are about level.', 'Feet shoulder-width apart, toes slightly out.',
      'Sit straight down, keeping the elbows up and the chest tall.', 'Stand up, driving the elbows up.'],
    mistake:'Elbows dropping, which lets the bar roll forward and the back round.' },
  { title:'Squat', match:wordsIn(['squats?']), not:wordsIn(['hack', 'sissy', 'pistol', 'jump', 'zercher', 'overhead', 'box', 'smith', 'dumbbells?', 'machine', 'belt', 'wall']),
    steps:['Bar across your upper back, on the muscle and not the neck. Grip it tight and pull the shoulder blades together.',
      'Unrack, step back, and set your feet about shoulder-width apart, toes slightly out.',
      'Take a big breath into the belly, then sit down and back, knees tracking over the toes.', 'Go as deep as you can with a flat back, then drive up through the whole foot, keeping the chest up.'],
    mistake:'Knees collapsing inward on the way up, or the hips rising faster than the shoulders.' },
  { title:'Leg Press', match:wordsIn(['leg press']),
    steps:['Sit with your back and hips flat against the pad and your feet shoulder-width apart in the middle of the platform.',
      'Release the safety and lower until your knees reach about 90 degrees, or as far as your hips stay on the pad.',
      'Press through the whole foot until the legs are nearly straight.', 'Stop short of locking the knees hard.'],
    mistake:'Lowering so far that the hips lift off the seat and the lower back rounds.' },
  { title:'Leg Extension', match:wordsIn(['leg extensions?']),
    steps:['Set the seat so your knees line up with the machine’s pivot and the pad sits on your lower shins.', 'Extend until the legs are straight, squeezing the quads.',
      'Lower slowly, under control, to just short of the stack resting.'],
    mistake:'Swinging the weight up with momentum instead of lifting it.' },
  { title:'Leg Curl', match:wordsIn(['(leg|hamstring) curls?']),
    steps:['Line your knees up with the pivot and set the pad just above the heels.', 'Curl the pad toward your glutes, keeping your hips down.',
      'Pause briefly at the top, then lower slowly until the legs are nearly straight.'],
    mistake:'Lifting the hips off the pad to cheat the weight up.' },
  { title:'Lunge', match:wordsIn(['lunges?']),
    steps:['Take a long step, then lower straight down until the back knee almost touches the floor.', 'Keep your torso upright and the front knee over the middle of the foot.',
      'Push through the front foot to return, or to step through into the next rep.'],
    mistake:'A step so short that the front knee travels far past the toes.' },
  { title:'Hip Thrust', match:wordsIn(['hip thrusts?']),
    steps:['Sit with your upper back against a bench and the bar over your hips, padded.', 'Feet flat and about hip-width apart, so the shins are upright at the top.',
      'Drive through the heels and lift the hips until the body is a straight line from knees to shoulders.', 'Squeeze the glutes for a moment at the top, with the chin tucked, then lower.'],
    mistake:'Arching the lower back at the top instead of getting there with the glutes.' },
  { title:'Calf Raise', match:wordsIn(['calf raises?']),
    steps:['Stand with the balls of your feet on a step or the machine’s platform and the heels hanging off.', 'Lower the heels as far as you comfortably can for a full stretch.',
      'Rise as high as possible onto your toes, pause there, then lower slowly.'],
    mistake:'Bouncing at the bottom instead of pausing in the stretch.' },
  { title:'Bench Press', match:wordsIn(['bench press']), not:wordsIn(['dumbbells?', 'db', 'machine', 'cable', 'smith', 'incline', 'decline']),
    steps:['Lie with your eyes under the bar, shoulder blades pulled together and down, feet flat on the floor.',
      'Grip the bar a little wider than shoulder-width, with the wrists stacked over the forearms.',
      'Unrack, then lower the bar under control to the lower chest, with the elbows about 45 to 75 degrees from the body.',
        'Press it back up and slightly toward the face until the arms are straight.'],
    mistake:'Flaring the elbows straight out to the sides, or bouncing the bar off the chest.' },
  { title:'Dumbbell Bench Press', match:wordsIn(['dumbbell (\\w+ )*bench( press)?', 'db (\\w+ )*bench( press)?']),
    steps:['Sit with the dumbbells on your thighs, then lie back, kicking them up to your chest. Pull the shoulder blades together.', 'Press them up until the arms are straight over the shoulders.',
      'Lower until the upper arms are about level with the bench, elbows at roughly 45 to 75 degrees from the body.', 'Press back up without letting the dumbbells drift apart.'],
    mistake:'Lowering too far and letting the shoulders roll forward.' },
  { title:'Incline Press', match:wordsIn(['incline (\\w+ )*press', 'incline (\\w+ )*bench']),
    steps:['Set the bench to about 30 degrees; a steeper angle shifts the work toward the shoulders.',
      'Lie back with the shoulder blades pulled together, and press the weight up until the arms are straight.',
      'Lower with control to the upper chest, with the elbows at roughly 45 to 75 degrees from the body.', 'Press back up over the shoulders.'],
    mistake:'Setting the bench too steep, which turns it into a shoulder press.' },
  { title:'Machine Chest Press', match:wordsIn(['machine (\\w+ )*chest press', 'chest press( machine)?']),
    steps:['Set the seat so the handles are level with the middle of your chest.', 'Sit with your back flat to the pad and the shoulder blades pulled back.',
      'Press until your arms are nearly straight, then return slowly until you feel a stretch across the chest.'],
    mistake:'Setting the seat too high, so the handles sit near the shoulders.' },
  { title:'Overhead Press', match:wordsIn(['overhead press', 'military press', 'ohp', 'push press', 'standing (\\w+ )*press']), not:wordsIn(['tricep', 'triceps', 'dumbbells?', 'db']),
    steps:['Bar on the front of your shoulders, grip just outside them, elbows slightly in front of the bar.', 'Squeeze the glutes and brace the abs so the lower back stays put.',
      'Press the bar straight up, moving your head back out of the way and then through once it passes.', 'Lock out with the bar over the middle of your feet, shrugging the shoulders up at the top.'],
    mistake:'Leaning back to push the weight up, which turns it into a standing incline press.' },
  { title:'Dumbbell Shoulder Press', match:wordsIn(['(seated |standing )?dumbbell (\\w+ )*(shoulder |overhead )?press', 'arnold press', 'shoulder press']),
    steps:['Sit with your back supported, or stand with the abs braced, and hold the dumbbells at shoulder height with the palms forward.',
      'Press them up until the arms are straight, the weights meeting over the head.',
      'Lower slowly back to the shoulders, with the forearms upright.'],
    mistake:'Arching the lower back off the pad to get the weights up.' },
  { title:'Lateral Raise', match:wordsIn(['(lateral|side) raises?']),
    steps:['Hold light dumbbells at your sides with a slight bend in the elbows.', 'Raise your arms out to the sides until they are level with the shoulders, leading with the elbows.',
      'Lower slowly. Use a weight you can control.'],
    mistake:'Swinging the weights up with the body, or shrugging them up with the traps.' },
  { title:'Rear Delt Fly', match:wordsIn(['rear delt', 'reverse fl(y|ies|yes)']),
    steps:['Hinge forward with a flat back, or sit chest-down on an incline bench, with the arms hanging.',
      'With a slight bend in the elbows, raise the arms out to the sides until they are level with the back.',
      'Squeeze the shoulder blades together at the top and lower slowly.'],
    mistake:'Rowing the weight up with the elbows pulling back instead of swinging out.' },
  { title:'Face Pull', match:wordsIn(['face ?pulls?']),
    steps:['Set a rope on a cable at about face height and take a step back with the arms straight.', 'Pull the rope toward your face, with the hands finishing beside the ears and the elbows high.',
      'Squeeze the shoulder blades together, then return slowly.'],
    mistake:'Using too much weight and leaning back to haul it in.' },
  { title:'Barbell Row', match:wordsIn(['barbell rows?', 'bent[- ]over rows?', 'pendlay rows?', 'rows?']), not:wordsIn(['dumbbells?', 'db', 'cable', 'seated', 'machine',
      'upright', 'chest[- ]supported', 'single[- ]arm', 'one[- ]arm', 'inverted']),
    steps:['Hinge forward until your torso is near level, holding the bar with a grip just outside the knees.', 'Keep your back flat and the knees soft.',
      'Pull the bar to your lower ribs, driving the elbows back.', 'Lower under control until the arms are straight.'],
    mistake:'Standing up more with every rep, until it is a shrug.' },
  { title:'Dumbbell Row', match:wordsIn(['(single|one)[- ]arm (\\w+ )*dumbbell rows?', 'dumbbell rows?', 'db rows?']), not:wordsIn(['cable', 'chest[- ]supported']),
    steps:['Put one hand and the same-side knee on a bench, the other foot on the floor and the back flat.',
      'Let the dumbbell hang straight down, then pull it to your hip, with the elbow close to the body.',
      'Squeeze the shoulder blade back at the top, then lower with control.'],
    mistake:'Twisting the torso to swing the weight up.' },
  { title:'Chest-Supported Row', match:wordsIn(['chest[- ]supported (\\w+ )*rows?']),
    steps:['Lie face-down on an incline bench with the chest against the pad and the dumbbells hanging below.', 'Pull the weights up by driving the elbows back and up, towards your hips.',
      'Squeeze the shoulder blades together at the top, then lower fully.'],
    mistake:'Lifting the chest off the pad to use momentum.' },
  { title:'Cable Row', match:wordsIn(['(seated |single[- ]arm |one[- ]arm )?cable rows?', 'seated rows?']),
    steps:['Sit with your feet braced and your knees slightly bent, back upright and the arms straight, holding the handle.', 'Pull the handle to your lower stomach, driving the elbows back.',
      'Squeeze the shoulder blades together for a moment, then let the arms straighten slowly.'],
    mistake:'Rocking the torso back and forth to move the weight.' },
  { title:'Lat Pulldown', match:wordsIn(['lat pull[- ]?downs?', '(single|one)[- ]arm (\\w+ )*pull[- ]?downs?', 'pull[- ]?downs?']),
    steps:['Sit with your thighs under the pads, and grip the bar just wider than your shoulders.', 'Lean back slightly, with the chest up.',
      'Pull the bar down to your upper chest, driving the elbows down and back.', 'Let it rise slowly until the arms are straight.'],
    mistake:'Leaning far back and yanking the bar down, which turns it into a row.' },
  { title:'Pull-up', match:wordsIn(['pull[- ]?ups?', 'chin[- ]?ups?']),
    steps:['Hang from the bar with straight arms, with a shoulder-width or slightly wider overhand grip (an underhand grip for a chin-up).',
      'Pull your shoulder blades down first, then pull the chest toward the bar.',
      'Get your chin over the bar, then lower all the way to straight arms.'],
    mistake:'Kipping, or stopping short of the full hang at the bottom.' },
  { title:'Dip', match:wordsIn(['dips?']),
    steps:['Support yourself on the bars with straight arms and the shoulders down, away from the ears.', 'Lean slightly forward for more chest, or stay upright for more triceps.',
      'Lower until the upper arms are about level with the floor.', 'Press back up to straight arms.'],
    mistake:'Dropping so deep that the shoulders roll forward and ache.' },
  { title:'Push-up', match:wordsIn(['push[- ]?ups?']),
    steps:['Hands just wider than your shoulders, body in a straight line from head to heels.', 'Squeeze the glutes and the abs so the hips do not sag.',
      'Lower until your chest is just above the floor, with the elbows about 45 degrees from the body.', 'Push back up to straight arms.'],
    mistake:'Sagging hips, or stopping well short of the floor.' },
  { title:'Hammer Curl', match:wordsIn(['hammer curls?']),
    steps:['Stand holding the dumbbells at your sides with the palms facing each other.', 'Curl them up without turning the wrists, keeping the elbows by your sides.',
      'Lower slowly to straight arms.'],
    mistake:'Swinging the weights up by leaning back.' },
  { title:'Curl', match:wordsIn(['(bicep|biceps|dumbbell|barbell|ez[- ]bar|cable|incline)?\\s?curls?']), not:wordsIn(['leg', 'hamstring', 'wrist', 'lying', 'seated leg', 'nordic']),
    steps:['Stand with the weights at your sides, palms forward and elbows tucked against the ribs.', 'Curl them up, with only the forearms moving, until the biceps are fully squeezed.',
      'Lower slowly all the way to straight arms.'],
    mistake:'Swinging the body, or letting the elbows drift forward to shorten the range.' },
  { title:'Overhead Tricep Extension', match:wordsIn(['overhead (\\w+ )*(tricep|triceps) extensions?', '(tricep|triceps) overhead', 'french press']),
    steps:['Hold one dumbbell, or a rope on a cable, with both hands overhead and the elbows pointing forward.', 'Lower the weight behind your head by bending only at the elbows.',
      'Extend until the arms are straight, squeezing the triceps.'],
    mistake:'Letting the elbows flare out wide, or arching the back.' },
  { title:'Tricep Pushdown', match:wordsIn(['(tricep|triceps) pushdowns?', 'pushdowns?', '(single|one)[- ]arm (\\w+ )*pushdowns?']),
    steps:['Stand close to the cable, with the elbows pinned to your sides.', 'Push the handle down until the arms are straight, squeezing the triceps.',
      'Let it rise slowly until the forearms are about level, with the elbows still pinned.'],
    mistake:'Letting the elbows travel forward and back, so the shoulders do the work.' },
  { title:'Hanging Leg Raise', match:wordsIn(['hanging (\\w+ )*raises?', '(leg|knee) raises?']),
    steps:['Hang from a bar with straight arms and the shoulders pulled slightly down.', 'Raise your legs, bent for an easier version and straight for a harder one, until the hips curl up.',
      'Lower slowly without swinging.'],
    mistake:'Swinging the legs up with momentum instead of curling the pelvis.' },
  { title:'Plank', match:wordsIn(['planks?']),
    steps:['Rest on your forearms with the elbows under the shoulders, and the body in a straight line.', 'Squeeze the glutes and the abs, pulling the ribs down toward the hips.',
      'Hold, breathing steadily, and stop when your hips start to sag.'],
    mistake:'Hips piking up or sagging toward the floor.' },
  { title:'Pallof Press', match:wordsIn(['pallof']),
    steps:['Stand sideways to a cable set at chest height, holding the handle against your chest with both hands.', 'Step away so there is tension, with the feet shoulder-width apart.',
      'Press the handle straight out and hold for a moment, resisting the cable pulling you around.', 'Bring it back in with control.'],
    mistake:'Twisting toward the cable as the arms extend.' }
];

// The guide for an exercise's name, or null when no entry fits.
function guideFor(name) {
  const text = String(name || '');
  return exerciseGuides.find(guide => guide.match.test(text) && !(guide.not && guide.not.test(text))) || null;
}

// A video search for the exercise, for a demonstration. Opened by the person tapping the link, so the app itself makes no
// request to anyone else.
function demoSearchUrl(name) {
  return `https://www.youtube.com/results?search_query=${encodeURIComponent(`${String(name || '').trim()} exercise form`)}`;
}
